version: '2'
services:
  rouber:
    image: rouber:0.0.1
    environment:
      DB_HOSTNAME: db
    ports:
      - '8081:8081'
    build:
      context: rouber
    depends_on:
      - db
  payments:
    image: payments:0.0.1
    environment:
      DB_HOSTNAME: db
    ports:
      - '8082:8082'
    build:
      context: core-payments
    depends_on:
      - db
      - rouber
  db:
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Twist3r:1
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local